<?xml version='1.0'?>

<!DOCTYPE widgets [

	  <!ELEMENT widgets (widget*)>

	  <!ELEMENT widget (overview,usage,properties,children,events,actions,clientprops,sample)>

	  <!ELEMENT overview (ANY)>

	  <!ELEMENT usage (ANY)>

	  <!ELEMENT properties (property*)>

	  <!ELEMENT property (ANY)>

	  <!ELEMENT children (child*)>

	  <!ELEMENT child (childproperty*)>

	  <!ELEMENT childproperty (ANY)>

	  <!ELEMENT events (event*)>

	  <!ELEMENT event (ANY)>

	  <!ELEMENT actions (action*)>

	  <!ELEMENT action (ANY)>

	  <!ELEMENT clientprops (clientprop*)>

	  <!ELEMENT clientprop (ANY)>

	  <!ELEMENT sample (#PCDATA)>



	  <!ATTLIST widget    

		    name           ID         #REQUIRED

		    type           CDATA      #REQUIRED

		    description    CDATA      #IMPLIED

		    visual         (yes|no)   #IMPLIED

		    formelement    (yes|no)   #IMPLIED

		    container      (yes|no)   #IMPLIED

		    osrcclient     (yes|no)   #IMPLIED

		    >

	  <!ATTLIST property

		    name           CDATA      #REQUIRED

		    type           CDATA      #REQUIRED

		    >

	  <!ATTLIST child

		    type           CDATA      #REQUIRED

		    >

	  <!ATTLIST childproperty

		    name           CDATA      #REQUIRED

		    type           CDATA      #REQUIRED

		    >

	  <!ATTLIST event

		    name           CDATA      #REQUIRED

		    >

	  <!ATTLIST action

		    name           CDATA      #REQUIRED

		    >

	  <!ATTLIST clientprop

		    name           CDATA      #REQUIRED

		    type           CDATA      #REQUIRED

		    >

]>

<widgets>

	<widget name="autolayout" type="widget/autolayout" description="Container which automatically positions its children" visual="yes" formelement="no" container="yes" osrcclient="no">

		<overview>

			<p>The autolayout widget is used to automatically position widgets without having to explicitly provide x, y, width, and height values for those widgets.  Most of the layout in Centrallix is done on a coordinate basis (although the automatic resize logic adjusts those coordinates to fit the target application or component render size).  The autolayout widget provides the capability to do nested gui layout in Centrallix, where the coordinate positions of the widgets are computed automatically.</p>

			<p>Normally, the autolayout widget is used not as "widget/autolayout", but as "widget/hbox" or "widget/vbox", two synonyms for this widget which also set the layout direction (horizontal or vertical).</p>

			<p>A "hbox" widget stacks its children horizontally one after the other, while a "vbox" widget stacks its children vertically from the top down.  The spacing between children can be set, and the size of each child can be either independently set per-child, or it can be set by virtue of the geometry of the autolayout widget.</p>

			<p>The autolayout widget supports having multiple rows or columns of widgets.  That is, if a "vbox" widget fills up vertically, it can resume adding children to a second vertical column should there be space to the right of the original column of widgets.  For this to work, the width of the columns (for a vbox) or the height of the rows (for an hbox) must be specified.</p>

		</overview>

		<usage>

			<p>The autolayout widget can occur any place that a visual widget can be placed.  As it is a container, it can also contain both visual and nonvisual widgets and containers.</p>

		</usage>

		<properties>

			<property name="align" type="string">Sets the alignment of text  can have left (default) right or center.</property>
		
			<property name="cellsize" type="integer">For an hbox, this is the width to use for the child widgets (unless otherwise specified by the child widget).  For a vbox, this refers to the height to use for child widgets unless otherwise specified.</property>

			<property name="column_width" type="integer">This specifies the width of columns for a vbox -- should the first column of widgets fill up, a second column will be started at this offset from the start of the first column.</property>

			<property name="height" type="integer">Height, in pixels, of the autolayout area.  If omitted, it defaults to the maximum available height for the given width, without overlapping other visible widgets.  If both width and height are unspecified, Centrallix will chose a width and height that maximize the available autolayout area.</property>

			<property name="justify" type="string">Makes the text fill page (justifies text - google it if you need).</property>
			
			<property name="row_height" type="integer">This specifies the height of rows for an hbox -- should the first row of widgets fill up horizontally, a second row will be started beneath the first one, at this vertical offset from the start of the first row.</property>

			<property name="spacing" type="integer">The spacing, in pixels, between widgets.  For an hbox, this refers to the horizontal spacing between children.  For a vbox, this refers to the vertical spacing.</property>

			<property name="style" type="string">Either "hbox" or "vbox".  Not needed if the widget is created via "widget/hbox" or "widget/vbox".</property>

			<property name="x" type="integer">X-coordinate of the upper left corner of the autolayout area.</property>

			<property name="y" type="integer">Y-coordinate of the upper left corner of the autolayout area.</property>

			<property name="width" type="integer">Width, in pixels, of the autolayout area.  If omitted, it defaults to the maximum available width for the given height, without overlapping other visible widgets.</property>

		</properties>

		<children>

			<child type="any">

				<childproperty name="autolayout_order" type="integer">An optional property, this allows the layout sequence of child widgets to be controlled, and the children are placed in ascending order.  If unspecified, this defaults to a value of 100 for the first child encountered, or to N+1 where N is the autolayout sequence of the most recent child widget encountered.</childproperty>
				
				<childproperty name="height" type="integer">Height, in pixels, of the child.</childproperty>
				
				<childproperty name="width" type="integer">Width, in pixels, of the child.</childproperty>

			</child>

		</children>

		<!--<events>

		</events>

		<actions>

		</actions>

		<clientprops>

		</clientprops>-->

		<sample>

		<![CDATA[

// Here is a vbox which can have up to three

// vertical columns of widgets; the columns will

// fill up one at a time.

vbox1 "widget/vbox"

	{

	x=0; y=0; width=600; height=200;

	spacing=5; column_width=200;

	}

		]]>

		</sample>

	</widget>

	<widget name="button" type="widget/button" visual="yes" container="no" formelement="no" description="A multipurpose button">

	    <overview>

		<p>Combines the functionality of the textbutton and imagebutton, as well as adding the ability to have both text and image displayed in a button.</p>

	    </overview>

	    <usage>

		<p>A Button can be placed inside any visible container, but only nonvisual widgets can be placed within it.  Properties that don't apply to the button's type are ignored.</p>

	    </usage>

	    <properties>

		<property name="bgcolor" type="string">A color, RGB or named, to be used as the button's background.If neither bgcolor nor background are specified, the button is transparent.</property>

		<property name="clickimage" type="string">The ObjectSystem pathname of the image to be shown when the user clicks the imagebutton.  Defaults to 'image' if not specified.</property>

		<property name="disable_color" type="string">A color, RGB or named, to be used for the button's text when it is disabled.</property>

		<property name="disabledimage" type="string">The ObjectSystem pathname of the image to be shown when the imagebutton is disabled.  Defaults to 'image' if not specified.</property>

		<property name="enabled" type="yes/no or expr">Whether the button is enabled (can be clicked).  Default is 'yes'.  Also supports dynamic runclient() expressions allowing the enabled status of the button to follow the value of an expression.</property>

		<property name="fgcolor1" type="string">A color, RGB or named, for the text on the button.  Default "white".</property>

		<property name="fgcolor2" type="string">A color, RGB or named, for the text's 1-pixel drop-shadow.  Default "black".</property>

		<property name="height" type="integer">Height, in pixels, of the text button.</property>

		<property name="image" type="string">The pathname of the image to be shown when the button is "idle".</property>

		<property name="pointimage" type="string">The pathname of the image to be shown when the button is pointed-to.  Defaults to  the 'image' if not specified.</property>
		
		<property name="spacing" type="integer">The distance between the image and text if applicable.</property>

		<property name="text" type="string">The text to appear on the button.</property>

		<property name="tristate" type="yes/no">Whether or not the button is tri-state (does not display a raised border until the user points at it). Default is yes.</property>

		<property name="type" type="string">There are currently 7 different types.  1) text 2) image 3) topimage (image above text) 4) rightimage 5) leftimage 6) bottomimage 7) textoverimage (text over image background).</property>	

		<property name="width" type="integer">The width, in pixels, of the text button.</property>

		<property name="x" type="integer">X-coordinate of the upper left corner of the button, relative to its container.</property>

		<property name="y" type="integer">Y-coordinate of the upper left corner of the button, relative to its container.</property>

	    </properties>
		
		<!--<children>

		</children>-->

		<events>
		
			<event name="Click">This event occurs when the user clicks the widget. No parameters are available from this event.</event>

			<event name="MouseDown">This event occurs when the user presses the mouse button on the widget.  This differs from the 'Click' event in that the user must actually press and release the mouse button on the widget for a Click event to fire, whereas simply pressing the mouse button down will cause the MouseDown event to fire.</event>

			<event name="MouseMove">This event occurs when the user moves the mouse pointer while it is over the widget.  The event will repeatedly fire each time the pointer moves.</event>

			<event name="MouseOver">This event occurs when the user first moves the mouse pointer over the widget.  It will not occur again until the user moves the mouse off of the widget and then back over it again.</event>

			<event name="MouseOut">This event occurs when the user moves the mouse pointer off of the widget.</event>
			
			<event name="MouseUp">This event occurs when the user releases the mouse button on the widget.</event>

		</events>

		<!--<actions>

		</actions>

		<clientprops>

		</clientprops>-->

		<sample>

		<![CDATA[

		]]>

		</sample>

	</widget>

	<widget name="calendar" type="widget/calendar" description="Calendar-type view of event/schedule type data in an objectsource" visual="yes" formelement="no" container="no" osrcclient="yes">

		<overview>

			<p>The calendar widget is used to present event/schedule types of data in a year, month, week, or day format.  The data for the events on the calendar is obtained from an objectsource's query results, and as such, can be controlled via queries and other forms/tables associated with the same objectsource.  The four formats are listed below and can be selected during app run-time.</p>

			<ul>

			    <li><b>Year</b> - Presents twelve months at a time in a low-detail type of setting; when events occur on a day, the day is highlighted, but no more data than that is displayed.  If the user points the mouse at a given day, it will display in a popup "tooltip" type of manner the events associated with that day.  If more than one year's worth of data is in the objectsource's replica, then multiple years are displayed one after the other.  Each year is displayed as four rows of three months each, in traditional calendar format.</li>

			    <li><b>Month</b> - Presents one month's worth of data in a medium-detail display.  For each month with data in the objectsource, the calendar will display the month as multiple rows, each row containing one week's worth of days.  The calendar will attempt to display the various entries for each day, in order of priority, but will limit the amount of data displayed to keep the boxes for the days approximately visually square.  Pointing at a day will show the events for the day in a popup, and pointing at an event in the day will show the details for that event.</li>

			    <li><b>Week</b> - Presents one week's worth of data in a high-detail display.  For each week with data in the objectsource, the calendar will display the week as seven days with a large vertical extent capable of displaying all events for the day.  The left edge of the display will contain times during the day for the day's events to line up with.</li>

			    <li><b>Day</b> - Presents an entire day's worth of data in a high-detail display.  For each day with data in the objectsource, the calendar will display the day in full-width, with the day's events listed chronologically from top to bottom.</li>

			</ul>

			<p>It should be noted that all of the data for the calendar must fit into the objectsource, or else the calendar will not display all of the available data.  In this manner the calendar's display must be controlled via the objectsource's data.</p>

		</overview>

		<usage>

			<p>The calendar widget can be placed inside of any visual container, but because its height can change, it is often placed inside of a scrollpane widget.  This widget may not contain other visual widgets.</p>

		</usage>

		<properties>

			<property name="background" type="string">An image for the background of the calendar widget.  Should be an ObjectSystem path.</property>

			<property name="bgcolor" type="string">A color, either named or numeric (RGB), for the background of the calendar.  If neither bgcolor nor background are specified, the calendar's background is transparent.</property>

			<property name="displaymode" type="string">The visual display mode of the calendar - can be 'year', 'month', 'week', or 'day' (see the overview, above, for details on these modes).  Defaults to 'year'.</property>

			<property name="eventdatefield" type="string">The name of the date/time field in the datasource containing the event date/time.  A mandatory field.</property>

			<property name="eventdescfield" type="string">The name of the string field in the datasource containing the event's full description.  If not supplied, descriptions will be omitted.</property>

			<property name="eventnamefield" type="string">The name of the string field in the datasource containing the event's short name.  A mandatory field.</property>

			<property name="eventpriofield" type="string">The name of the integer field in the datasource containing the event's priority.  If not supplied, priority checking is disabled.</property>

			<property name="height" type="integer">The height of the calendar, in pixels.  If not specified, the calendar may grow vertically an indefinite amount in order to display its given data.  If specified, however, the calendar will be limited to that size.</property>

			<property name="minpriority" type="integer">The minimum priority level for events that will be displayed on the calendar; the values for this integer depend on the nature of the 'priority' field in the data source; only events with priority values numerically higher than or equal to this minimum priority will be displayed.  Defaults to 0.</property>
			
			<property name="textcolor" type="string">The color of the words in the calendar.</property>
			
			<property name="width" type="integer">The width of the calendar, in pixels.</property>

			<property name="x" type="integer">X-coordinate of the upper left corner of the calendar, default is 0.</property>

			<property name="y" type="integer">Y-coordinate of the upper left corner of the calendar, default is 0.</property>

		</properties>

		<!--<children>

		</children>-->

		<events>
		
			<event name="MouseDown">This event occurs when the user presses the mouse button on the widget.  This differs from the 'Click' event in that the user must actually press and release the mouse button on the widget for a Click event to fire, whereas simply pressing the mouse button down will cause the MouseDown event to fire.</event>

			<event name="MouseMove">This event occurs when the user moves the mouse pointer while it is over the widget.  The event will repeatedly fire each time the pointer moves.</event>
		
			<event name="MouseOut">This event occurs when the user moves the mouse pointer off of the widget.</event>

			<event name="MouseOver">This event occurs when the user first moves the mouse pointer over the widget.  It will not occur again until the user moves the mouse off of the widget and then back over it again.</event>

			<event name="MouseUp">This event occurs when the user releases the mouse button on the widget.</event>

		</events>

		<!--<actions>

		</actions>

		<clientprops>

		</clientprops>-->

		<sample>

		<![CDATA[

		]]>

		</sample>

	</widget>

	<widget name="chart" type="widget/chart" description="Chart widget for graphing data from an ObjectSource, using the ChartJS library." visual="yes" formelement="no" container="no">
		<overview>
			<p>A chart widget is used to display charts and graphs of data. It uses the Chart.js library.</p>
		</overview>

		<usage>
			<p>The chart widget can be placed inside of any visual container, and will attach itself to any objectsource widget that contains it (whether directly or indirectly).  Charts may not contain visual widgets.</p>
		</usage>

		<properties>
			<property name="chart_type" type="string">Currently supported types are "bar", "line", "scatter", and "pie". Defaults to "bar". Chart.js supports much more than this, so new types could be added with relative ease.</property>
			<property name="legend_position" type="string">The position of the legend on the chart. May be "top", "botton", "left", or "right".</property>
			<property name="objectsource" type="string">The name of the ObjectSource widget which will supply data for the chart. We recommend that you do not specify this directly but instead embed the chart widget within a parent ObjectSource, directly or indirectly. If not specified, the chart will look for an ObjectSource in its parents.</property>
			<property name="start_at_zero" type="boolean">Set to false if you want the y axis to start at the lowest data value. Default is true.</property>
			<property name="title" type="string">The title of the chart. Default is none.</property>
			<property name="titlecolor" type="string">A color, RGB or named, of the chart title.</property>
			<property name="title_size" type="integer">The size, in points, of the title font.</property>
		</properties>

		<children>
			<child type="widget/chart-series">
				<childproperty name="chart_type" type="string">Chart.js has limited support for having multiple chart types on the same axes. The outer chart type must still be specified if this is set.</childproperty>
				<childproperty name="color" type="string">A color, RGB or named, for the chart element (ex: line) which represents this series.</childproperty>
				<childproperty name="fill" type="boolean">Set to false to remove the color fill beneath a line chart. Default is true.</childproperty>
				<childproperty name="label" type="string">A label for the data series.</childproperty>
				<childproperty name="x_column" type="string">Which column in the data should be used for the x axis? By default, the chart will pick one for you.</childproperty>
				<childproperty name="y_column" type="string">Which column in the data should be used for the y axis? By default, the chart will pick one for you.</childproperty>
			</child>

			<child type="widget/chart-axis">
				<childproperty name="axis" type="string">Which axis is this? Possible values are "x" and "y". Default is "x".</childproperty>
				<childproperty name="label" type="string">A label for the axis. Default is none.</childproperty>
			</child>
		</children>

		<sample>

		<![CDATA[

$Version=2$
// Here is a simple chart.
chart "widget/chart"
	{
	x=0; y=0;
	width=483;
	height=650;
	chart_type="bar";
	title="Sample Chart";
	titlecolor="black";
	legend_position="right";

	series1 "widget/chart-series" { color="blue"; }

	series2 "widget/chart-series"
		{
		fill=no;
		chart_type="line";
		x_column="name";
		y_column="permissions";
		}

	x_axis "widget/chart-axis" { axis="x"; label="X"; }
	}

		]]>

		</sample>
	</widget>

	<widget name="checkbox" type="widget/checkbox" description="Form element capable of selecting an on/off, yes/no, true/false, etc., type of value, via a visual 'check mark'." visual="yes" formelement="yes" container="no">

		<overview>

			<p>The checkbox widget is used to display a value that can be either true or false (or on/off, yes/no, etc.).It displays as a simple clickable check box.</p>

		</overview>

		<usage>

			<p>The checkbox widget can be placed inside of any visual container, and will attach itself to any form widget that contains it (whether directly or indirectly).  Checkboxes may not contain visual widgets.</p>

		</usage>

		<properties>

			<property name="checked" type="yes/no">Whether this checkbox should be initially checked or not.  Default 'no'.</property>
			
			<property name="enabled" type="boolean">This allows the checkbox to be changed.</property>

			<property name="fieldname" type="string">Name of objectsource field that should be associated with this checkbox.</property>

			<property name="form" type="string">The name of the form that this checkbox is associated with.</property>
			
			<property name="x" type="integer">X-coordinate of the upper left corner of the checkbox, default is 0.</property>

			<property name="y" type="integer">Y-coordinate of the upper left corner of the checkbox, default is 0.</property>

		</properties>

		<!--<children>

		</children>-->

		<events>

			<event name="Click">This event occurs when the user clicks the checkbox. No parameters are available from this event.</event>

			<event name="DataChange">This event occurs when the user has modified the data value of the checkbox (clicked or unclicked it).</event>

			<event name="MouseDown">This event occurs when the user presses the mouse button on the checkbox.  This differs from the 'Click' event in that the user must actually press and release the mouse button on the checkbox for a Click event to fire, whereas simply pressing the mouse button down will cause the MouseDown event to fire.</event>

			<event name="MouseMove">This event occurs when the user moves the mouse pointer while it is over the checkbox.  The event will repeatedly fire each time the pointer moves.</event>

			<event name="MouseOut">This event occurs when the user moves the mouse pointer off of the checkbox.</event>

			<event name="MouseOver">This event occurs when the user first moves the mouse pointer over the checkbox.  It will not occur again until the user moves the mouse off of the checkbox and then back over it again.</event>

			<event name="MouseUp">This event occurs when the user releases the mouse button on the checkbox.</event>

		</events>

		<actions>
		
			<action name="SetValue">This takes a given value and sets the check box value to it.</action>

		</actions>

		<!--<clientprops>

		</clientprops>-->

		<sample>

		<![CDATA[

$Version=2$

// Here are two checkboxes.

checkbox_test "widget/page"

	{

	background="/sys/images/slate2.gif";

	testcheck2 "widget/checkbox"

		{

		x = 20; y = 40;

		}

	testcheck "widget/checkbox"

		{

		x = 20; y = 20;

		}

	}

		]]>

		</sample>

	</widget>
	
	<widget name="childwindow" type="widget/childwindow" visual="yes" formelement="no" container="yes" osrcclient="no" description="A dialog or application window which is a lightweight movable container.">

		<overview>

			<p>The childwindow provides the capability of creating a popup dialog or application window within a web page.  The window is not actually a separate browser window, but rather a movable container that can appear "floating" above the rest of the Centrallix application.They can take on one of two styles;"dialog" and "window", which currently relate only to how the window border and titlebar are drawn.  The windows support windowshading (double-clicking on the titlebar to "rollup" or "rolldown" the window contents).</p>

			<p>These "windows" currently do not support multiple instantiation.</p>

		</overview>

		<usage>

			<p>Childwindows are normally coded at the top-level of an application, since if they are placed within containers, the container limits where the window can be moved (the window is clipped by its container).  However, if the "toplevel" property is enabled, then the window floats at the top level of other widgets regardless of the size and location of its container in the application or component (thus the window is not clipped by its container).</p>

			<p>These windows can contain other visual and nonvisual widgets.</p>

		</usage>

		<properties>

		    <property name="background" type="string" subtype="image">A background image for the body of the window.</property>

		    <property name="bgcolor" type="string" subtype="color">A color, RGB or named, to be used as the window body's background.If neither transparent.</property>
						
			<property name="border_color" type="string">A color that outlines window.</property>
			
			<property name="border_radius" type="integer">A radius that describes the sharpness of the corners of the window (smaller means sharper).</property>

			<property name="border_style" type="string">Determines the look of the outline.</property>
			
			<property name="closetype" type="string">Decides wither the screen closes widthwise (1) or heightwise (2).</property>
			
			<property name="gshade" type="string">Acts as a boolean to declare if the window is shaded or not (all but title bar minimized).</property>

		    <property name="hdr_background" type="string" subtype="color">A background image for the titlebar of the window.</property>

		    <property name="hdr_bgcolor" type="string" subtype="color">A color, RGB or named, for the titlebar of the window.</property>

		    <property name="height" type="integer">Height, in pixels, of the window.</property>

		    <property name="icon" type="string">A pathname to an icon to be used in the upper left corner of the window.  If unspecified, the default "CX" ichthus icon is used instead.</property>

		    <property name="modal" type="yes/no">If "yes", the window is modal (and IsModal need not be passed to "Open").  A modal window will force the user to close the window before anything else in the application can be accessed.</property>
			
			<property name="shadow_angle" type="integer">The placement of the shadow described as a rotational transformation with respect to the window.</property>
			
			<property name="shadow_color" type="string">The color of the shadow.</property>

			<property name="shadow_radius" type="integer">A radius that describes the sharpness of the corners of the shadow (smaller means sharper).</property>

			<property name="shadow_offset" type="integer">The placement of the shadow with respect to the window.</property>

		    <property name="style" type="string">Either "dialog" or "window", and determines the style of the window's border.</property>

		    <property name="textcolor" type="string" subtype="color">The color for the titlebar's text (window title).  Default "black".</property>

		    <property name="title" type="string">The window's title.</property>

		    <property name="titlebar" type="yes/no">Whether the window will have a titlebar (and the close "X" in the upper right corner of the window). Default "yes".</property>
			
		    <property name="toplevel" type="yes/no">If "yes", the window will float above all other widgets in the application, otherwise it will be clipped by its own container.</property>

		    <property name="visible" type="boolean">The window is initially visible on screen. The window has an action which can "true".</property>

		    <property name="width" type="integer">Width, in pixels, of the window.</property>

		    <property name="x" type="integer">X-coordinate of the upper left corner of the window, relative to its container.</property>

		    <property name="y" type="integer">Y-coordinate of the upper left corner of the window, relative to its container.</property>

		</properties>

		<actions>

		    <action name="Close">Closes the window.  Note that widgets inside the window may choose to veto the Close operation: for example, if there is unsaved data in a form.</action>
